# Reference: https://github.com/pinterest/PINRemoteImage/blob/master/.travis.yml
#            https://github.com/Alamofire/Alamofire/blob/master/.travis.yml
language: swift
osx_image: xcode10.2
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8

    - PROJECT="Ji.xcodeproj"
    - IOS_FRAMEWORK_SCHEME="Ji iOS"
    - MACOS_FRAMEWORK_SCHEME="Ji OSX"
    - TVOS_FRAMEWORK_SCHEME="Ji tvOS"
    - WATCHOS_FRAMEWORK_SCHEME="Ji watchOS"

  matrix:
    # iOS
    - DESTINATION="OS=12.2,name=iPhone Xs"          SCHEME="$IOS_FRAMEWORK_SCHEME"
    - DESTINATION="OS=11.4,name=iPhone X"           SCHEME="$IOS_FRAMEWORK_SCHEME"

    # macOS
    - DESTINATION="arch=x86_64"                     SCHEME="$MACOS_FRAMEWORK_SCHEME"

    # tvOS
    - DESTINATION="OS=12.2,name=Apple TV 4K"     SCHEME="$TVOS_FRAMEWORK_SCHEME"
    - DESTINATION="OS=11.4,name=Apple TV 4K"     SCHEME="$TVOS_FRAMEWORK_SCHEME"

    # watchOS
    - DESTINATION="OS=5.2,name=Apple Watch Series 4 - 44mm"  SCHEME="$WATCHOS_FRAMEWORK_SCHEME"
    - DESTINATION="OS=4.2,name=Apple Watch Series 3 - 42mm"  SCHEME="$WATCHOS_FRAMEWORK_SCHEME"

before_install:
  # - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  ## Build for Debug with tests
  - xcodebuild -project "$PROJECT" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug | xcpretty;

  ## Build for Release
  - xcodebuild -project "$PROJECT" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release | xcpretty;
